// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHQq3t7AE2oPeyKSO9O1Sf-qP1iQnz4dM',
    appId: '1:1041712138611:web:48d204ad563954b2b19d06',
    messagingSenderId: '1041712138611',
    projectId: 'money-minder-2023',
    authDomain: 'money-minder-2023.firebaseapp.com',
    storageBucket: 'money-minder-2023.appspot.com',
    measurementId: 'G-K9HBVENBK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsID39NBXtHwGfRioFdkUT0yWc3KWkhc8',
    appId: '1:1041712138611:android:506ee9418313557fb19d06',
    messagingSenderId: '1041712138611',
    projectId: 'money-minder-2023',
    storageBucket: 'money-minder-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArMormL3l-o_PVDTx8mup7XniWrZWJcl0',
    appId: '1:1041712138611:ios:17aab4cd9c15ad61b19d06',
    messagingSenderId: '1041712138611',
    projectId: 'money-minder-2023',
    storageBucket: 'money-minder-2023.appspot.com',
    iosBundleId: 'com.example.moneyMinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArMormL3l-o_PVDTx8mup7XniWrZWJcl0',
    appId: '1:1041712138611:ios:e46a0124c32e136cb19d06',
    messagingSenderId: '1041712138611',
    projectId: 'money-minder-2023',
    storageBucket: 'money-minder-2023.appspot.com',
    iosBundleId: 'com.example.moneyMinder.RunnerTests',
  );
}
