// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR_Ahd9w5JaNRmBSM1clws6iVN05kWIw4',
    appId: '1:1035233771278:web:01aaac30fffd797bd0a15f',
    messagingSenderId: '1035233771278',
    projectId: 'moneyminder-2bb80',
    authDomain: 'moneyminder-2bb80.firebaseapp.com',
    storageBucket: 'moneyminder-2bb80.appspot.com',
    measurementId: 'G-4TSX3828RE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh1YpoUflaAJptbtPQyu5hOyXewpNdJc0',
    appId: '1:1035233771278:android:26697cb6ee7f4574d0a15f',
    messagingSenderId: '1035233771278',
    projectId: 'moneyminder-2bb80',
    storageBucket: 'moneyminder-2bb80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8Bunt1Hf95CpOMBfoNXBoEMLqeSX-l7w',
    appId: '1:1035233771278:ios:0415656f035cdd77d0a15f',
    messagingSenderId: '1035233771278',
    projectId: 'moneyminder-2bb80',
    storageBucket: 'moneyminder-2bb80.appspot.com',
    iosBundleId: 'com.example.projectPrototype',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8Bunt1Hf95CpOMBfoNXBoEMLqeSX-l7w',
    appId: '1:1035233771278:ios:5f5633024316c4d1d0a15f',
    messagingSenderId: '1035233771278',
    projectId: 'moneyminder-2bb80',
    storageBucket: 'moneyminder-2bb80.appspot.com',
    iosBundleId: 'com.example.projectPrototype.RunnerTests',
  );
}
